version: '3.8'

services:
  postgres:
    container_name: store
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432' # Format: <Host Port>:<Container Port>

  apps:
    container_name: clothing_store
    image: yunusvaliev/clothing_store
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - '3003:${PORT}' # Format: <Host Port>:<Container Port>
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      ACCESS_TOKEN_TIME: ${ACCESS_TOKEN_TIME}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_TIME: ${REFRESH_TOKEN_TIME}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILDEV_USER: ${MAILDEV_USER}
      MAILDEV_PASS: ${MAILDEV_PASS}
      API_HOST: ${API_HOST}